SECRET_KEY = "6\x92\x89,y:\x92\x90\xa7*uN\x90\x0b\xd3'?\xb9I\xce\xac\xef]\xe2"  # generated by os.urandom(24)

SQLALCHEMY_DATABASE_URI = 'mysql://root:cfl@localhost:3306/Coffeel?charset=utf8'

DEBUG = True